# Generated by Django 3.2.9 on 2024-01-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRmjivXii4HjtyuaSeTbuZxX23TPkv701da9FplhGeyg&s', max_length=500),
        ),
    ]
