# Generated by Django 3.2.9 on 2024-01-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_item_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_name',
        ),
    ]
